name: Devops-vg

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  build-number: ${{GITHUB.RUN_NUMBER}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Build Docker image
        run: |
          docker build --build-arg BUILD_NUMBER=${{ env.build-number }} -t jatteliten/pokemon-list .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: |
          docker push jatteliten/pokemon-list
