name: Devops-vg

on:
  push:
    branches: [ "master" ]

env:
  build-number: ${{GITHUB.RUN_NUMBER}}

permissions: write-all
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.9'

      - name: Build
        run: ./gradlew clean build   

      - run: mv build/libs/Devops-vg-0.0.1-SNAPSHOT.jar build/libs/Devops-vg-1.${{ env.build-number }}.1.jar

      - run: mkdir staging && cp build/libs/Devops-vg-1.${{ env.build-number }}.1.jar staging/Devops-vg-1.${{ env.build-number }}.1.jar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t jatteliten/pokemon-list .

      - name: Push Docker image
        run: |
          docker push jatteliten/pokemon-list:latest
